(()=>{'use strict';
const D=window.ABSTRACT_MAP,F=window.RESEARCH_FRAMEWORK,$=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={methods:'Technical methods',mechanism:'Mechanistic studies',clinical:'Clinical statistics',engineering:'Microbial therapeutics',uncertain:'Unresolved',review:'Reviews / synthesis'};
const shortNames={methods:'Methods',mechanism:'Mechanism',clinical:'Clinical',engineering:'Engineering',uncertain:'Unresolved',review:'Review'};
const theme=getComputedStyle(document.documentElement),themeColor=name=>theme.getPropertyValue(name).trim();
const typePalette={methods:themeColor('--class-methods'),mechanism:themeColor('--class-mechanism'),clinical:themeColor('--class-clinical'),engineering:themeColor('--class-engineering'),uncertain:themeColor('--class-unresolved'),review:themeColor('--class-review')};
F.categories.forEach(c=>{c.color=typePalette[c.id];});
const actionNames={cohort:'Patient cohorts',association:'Statistical association',prediction:'Prediction models',external:'External validation',perturb:'Bacterial perturbation',pathway:'Host pathway intervention',rescue:'Rescue / add-back',model:'Cell / animal models',method:'Method development',microbe:'Microbial engineering',material:'Materials / delivery'};
const n=D.papers.length,bytes=Uint8Array.from(atob(D.matrix),c=>c.charCodeAt(0)),dv=new DataView(bytes.buffer),sim=(i,j)=>dv.getInt16((i*n+j)*2,true)/10000,cat=id=>F.categories.find(c=>c.id===id),canvas=$('#matrix'),ctx=canvas.getContext('2d'),dialog=$('#paper-dialog');
let selectedType='all',order=F.order.slice(),page=0,geometry=null,activeCell=[0,0],keyboardSelection=false,lookupSource=-1;const pageSize=20;
$('#total').textContent=n;$('#excluded-count').textContent=`${D.excluded.length} records excluded`;
$('#categories').innerHTML=`<button data-type="all" aria-pressed="true">All papers <b>${n}</b></button>`+F.categories.map(c=>`<button data-type="${c.id}" aria-pressed="false">${names[c.id]} <b>${c.count}</b></button>`).join('');
$('#matrix-types').innerHTML=F.categories.map(c=>`<span style="--type:${c.color}"><i aria-hidden="true"></i>${names[c.id]}</span>`).join('');
const hexRgb=value=>{const h=value.replace('#','');return [0,2,4].map(i=>parseInt(h.slice(i,i+2),16));};
let similarityStops=Array.from({length:8},(_,i)=>hexRgb(themeColor(`--similarity-${i}`)));
function similarityColor(v){v=Math.max(0,Math.min(1,v));const t=v*(similarityStops.length-1),i=Math.min(similarityStops.length-2,Math.floor(t)),f=t-i;return similarityStops[i].map((a,k)=>Math.round(a+(similarityStops[i+1][k]-a)*f));}
const selectedMatrixPalette={name:'Greys'};
$('#table-head').innerHTML='<tr><th class="paper-col" rowspan="2" scope="col">Paper / candidate type</th><th colspan="4" scope="colgroup">Clinical analysis</th><th colspan="4" scope="colgroup">Experimental interventions</th><th colspan="3" scope="colgroup">Methods & engineering</th></tr><tr>'+F.actions.map(a=>`<th scope="col">${actionNames[a.id]}</th>`).join('')+'</tr>';
function searchActive(){return !!$('#search').value.trim();}
function filter(){
 const q=$('#search').value.trim().toLowerCase();
 lookupSource=window.AtlasSearch.resolve(D.papers,q);
 if(q){
  selectedType='all';
  document.querySelectorAll('[data-type]').forEach(t=>t.setAttribute('aria-pressed',String(t.dataset.type==='all')));
  order=lookupSource>=0?window.AtlasSearch.related(D.papers,lookupSource,sim,.7).map(r=>r.index):F.order.filter(i=>(D.papers[i].title+' '+D.papers[i].doi+' '+D.papers[i].id).toLowerCase().includes(q));
 }else order=F.order.filter(i=>selectedType==='all'||F.rows[i].primary===selectedType);
 page=0;activeCell=[0,0];keyboardSelection=false;
 $('#hover').textContent='Select a cell to compare two papers. Use a type filter for a closer view.';
 renderNeighbors();update();
}
function renderNeighbors(){
 const panel=$('#neighbors');panel.hidden=!searchActive();
 if(panel.hidden){panel.innerHTML='';return;}
 if(lookupSource<0){
  panel.innerHTML=`<div class="lookup-source"><div><h2>${order.length?'Select a reference paper':'No matching paper'}</h2><p class="detail-meta">${order.length?'Choose a paper to find all abstracts with similarity > 0.7.':'Try an indexed DOI, paper title, or record ID.'}</p></div><button class="clear-search">Clear search</button></div><div class="related-list">${order.map(i=>`<article class="related-row"><div><button class="paper-title" data-reference="${i}">${E(D.papers[i].title)}</button><p class="detail-meta">${E(D.papers[i].year)} · ${E(D.papers[i].journal)} · ${E(D.papers[i].doi||D.papers[i].id)}</p></div></article>`).join('')}</div>`;
  return;
 }
 const source=D.papers[lookupSource];
 panel.innerHTML=`<div class="lookup-source"><div><span class="eyebrow">REFERENCE PAPER</span><button class="paper-title" data-source="${lookupSource}">${E(source.title)}</button><p class="detail-meta">${E(source.year)} · ${E(source.doi||source.id)}</p></div><button class="clear-search">Clear search</button></div><div class="neighbor-heading"><h3>Related papers</h3><span>${order.length} papers · similarity > 0.7 · includes the reference paper</span></div><div class="related-list">${order.map(i=>{const paper=D.papers[i],self=i===lookupSource;return `<article class="related-row"><div><button class="paper-title" data-neighbor="${i}">${E(paper.title)}</button><p class="detail-meta">${E(paper.year)} · ${E(paper.journal)} · ${E(paper.doi||paper.id)}${self?' · Reference paper':''}</p></div><div class="related-score"><span>Similarity</span><strong>${sim(lookupSource,i).toFixed(4)}</strong><button class="compare-neighbor" data-neighbor="${i}">${self?'Read abstract':'Compare abstracts'} ↗</button></div></article>`;}).join('')}</div>`;
}
$('#neighbors').onclick=e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.classList.contains('clear-search')){$('#search').value='';filter();$('#search').focus();}
 else if(b.dataset.reference!==undefined){$('#search').value=D.papers[+b.dataset.reference].id;filter();}
 else if(b.dataset.source!==undefined)show(+b.dataset.source);
 else if(b.dataset.neighbor!==undefined)show(lookupSource,+b.dataset.neighbor);
};
function update(){
 const searching=searchActive();
 $('.analysis-pair').hidden=searching;
 $('#categories').hidden=searching;
 $('.actions-section').hidden=searching&&lookupSource<0;
 $('#result-count').textContent=`${order.length} ${order.length===1?'paper':'papers'}`;
 $('#actions-description').textContent=lookupSource>=0?`${order.length} papers · similarity > 0.7 · includes the reference paper · highest similarity first.`:'Compare abstract-level study actions. Select a marker to inspect its source sentences.';
 if(!searching){draw();featureChart();}
 if(!searching||lookupSource>=0)table();
}
document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{if(lookupSource>=0)$('#search').value='';selectedType=b.dataset.type;document.querySelectorAll('[data-type]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));filter();});
$('#search').oninput=filter;
function featureChart(){const stats=window.FeatureStats.summarize(F.rows,order,F.actions);if($('#feature-sort').value==='frequency')stats.sort((a,b)=>b.matched-a.matched||a.id.localeCompare(b.id));const total=order.length;$('#feature-scope').textContent=`${selectedType==='all'?'All study types':names[selectedType]} · ${total} abstracts in the current selection`;$('#feature-chart').innerHTML=total?`<div class="feature-row feature-axis"><span>Research feature</span><span class="feature-ticks"><i>0%</i><i>25%</i><i>50%</i><i>75%</i><i>100%</i></span><span>Any match</span></div>`+stats.map(s=>{const pct=v=>100*v/total,desc=`${actionNames[s.id]}: ${s.hit} text matches, ${s.tentative} tentative-only matches, ${s.unknown} unknown, out of ${total} abstracts`;return `<button class="feature-row" data-feature="${s.id}" aria-label="${desc}. Open matching papers."><span class="feature-name">${actionNames[s.id]}</span><span class="feature-track" role="img" aria-label="${desc}"><i class="feature-hit" style="width:${pct(s.hit)}%"></i><i class="feature-tentative" style="width:${pct(s.tentative)}%"></i><i class="feature-unknown" style="width:${pct(s.unknown)}%"></i></span><span class="feature-value"><b>${s.matched}</b><small>${pct(s.matched).toFixed(1)}%</small></span></button>`;}).join(''):'<p class="empty">No matching abstracts. Clear the search or choose another type.</p>';}
$('#feature-sort').onchange=featureChart;
$('#feature-chart').onclick=e=>{const b=e.target.closest('[data-feature]');if(!b)return;const id=b.dataset.feature,ix=order.filter(i=>F.rows[i].actions[id].length);$('#dialog-title').textContent=actionNames[id];$('#detail').innerHTML=`<p class="detail-meta">${ix.length} of ${order.length} selected abstracts contain matching wording. Each paper is counted once. Select a paper to inspect its sentences.</p>`+(ix.length?ix.map(i=>`<article class="feature-paper"><button class="paper-title" data-feature-paper="${i}">${E(D.papers[i].title)}</button><p class="detail-meta">${E(D.papers[i].year)} · ${F.rows[i].actions[id].some(h=>!h.tentative)?'Text match':'Tentative wording only'}</p></article>`).join(''):'<p>No matching wording found. This does not establish that the experiment was absent.</p>');$('#detail').querySelectorAll('[data-feature-paper]').forEach(t=>t.onclick=()=>show(+t.dataset.featurePaper,null,id));if(!dialog.open)dialog.showModal();dialog.scrollTop=0;$('#close-dialog').focus();};
$('#feature-export').onclick=()=>{const stats=window.FeatureStats.summarize(F.rows,order,F.actions),csv='Feature,Text match,Tentative only,Unknown,Any match,Selected abstracts,Any match percent\r\n'+stats.map(s=>[actionNames[s.id],s.hit,s.tentative,s.unknown,s.matched,s.total,s.total?(100*s.matched/s.total).toFixed(2):''].join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='research-feature-statistics.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#matrix-export').onclick=()=>canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`paper-similarity-${selectedMatrixPalette.name.toLowerCase()}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');
function draw(){if(searchActive())return;const m=order.length;$('#matrix-empty').hidden=!!m;canvas.hidden=!m;if(!m){geometry=null;return;}const width=canvas.parentElement.clientWidth-24,size=Math.max(200,width),pad=32,end=8,plot=size-pad-end,ratio=window.devicePixelRatio||1;canvas.width=Math.round(size*ratio);canvas.height=Math.round(size*ratio);canvas.style.height=size+'px';ctx.setTransform(ratio,0,0,ratio,0,0);ctx.fillStyle='#fff';ctx.fillRect(0,0,size,size);geometry={size,pad,plot,m};const off=document.createElement('canvas');off.width=m;off.height=m;const oc=off.getContext('2d'),im=oc.createImageData(m,m);for(let y=0;y<m;y++)for(let x=0;x<m;x++){const v=Math.max(0,Math.min(1,sim(order[y],order[x]))),rgb=similarityColor(v),k=(y*m+x)*4;im.data[k]=rgb[0];im.data[k+1]=rgb[1];im.data[k+2]=rgb[2];im.data[k+3]=255;}oc.putImageData(im,0,0);ctx.imageSmoothingEnabled=false;ctx.drawImage(off,pad,pad,plot,plot);
 order.forEach((i,y)=>{const r=F.rows[i],pos=pad+y*plot/m,step=plot/m;ctx.fillStyle=cat(r.primary).color;ctx.fillRect(9,pos,8,step+.2);ctx.fillRect(pos,9,step+.2,8);ctx.fillStyle=r.secondary.length?cat(r.secondary[0]).color:'#edf1f4';ctx.fillRect(20,pos,5,step+.2);if(y&&r.primary!==F.rows[order[y-1]].primary){ctx.strokeStyle='#ffffffc0';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pad,pos);ctx.lineTo(pad+plot,pos);ctx.moveTo(pos,pad);ctx.lineTo(pos,pad+plot);ctx.stroke();}});
 if(keyboardSelection){const [y,x]=activeCell;ctx.strokeStyle='#132638';ctx.lineWidth=2;ctx.strokeRect(pad+x*plot/m-2,pad+y*plot/m-2,plot/m+4,plot/m+4);}
}
function table(){const limit=lookupSource>=0?Math.max(1,order.length):pageSize,start=page*limit,items=order.slice(start,start+limit);$('#table-body').innerHTML=items.length?items.map(i=>{const p=D.papers[i],r=F.rows[i];return `<tr><th scope="row"><button class="paper-title" data-paper="${i}" title="${E(p.title)}">${E(p.title)}</button><div class="paper-meta"><span>${E(p.year||'Year unavailable')}</span><span>${E(p.id)}</span>${lookupSource>=0?`<span>Similarity ${sim(lookupSource,i).toFixed(4)}${i===lookupSource?' · Reference paper':''}</span>`:''}<span class="type-badge" style="--type:${cat(r.primary).color}"><i aria-hidden="true"></i>${shortNames[r.primary]}</span></div></th>${F.actions.map(a=>{const hits=r.actions[a.id],state=hits.some(h=>!h.tentative)?'hit':hits.length?'tentative':'unknown',label=state==='hit'?`${hits.length} matching sentences`:state==='tentative'?`${hits.length} matches with tentative wording`:'Not found in abstract; unknown';return `<td><button class="cell ${state}" data-action="${a.id}" data-index="${i}" title="${actionNames[a.id]}: ${label}" aria-label="${E(p.id)} — ${actionNames[a.id]}: ${label}">${hits.length||'—'}</button></td>`;}).join('')}</tr>`;}).join(''):'<tr><td colspan="12" class="empty">No matching papers. Try another title or research type.</td></tr>';
 $('#page-info').textContent=items.length?`${start+1}–${start+items.length} of ${order.length} papers · ${lookupSource>=0?'highest similarity first':'ordered by type and similarity'}`:'0 papers';$('#page-number').textContent=`${order.length?page+1:0} / ${Math.ceil(order.length/limit)}`;$('#prev').disabled=page===0;$('#next').disabled=start+limit>=order.length;
}
$('#table-body').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.paper!==undefined)show(+b.dataset.paper);else if(b.dataset.action)show(+b.dataset.index,null,b.dataset.action);};
function movePage(delta){page+=delta;table();$('.table-scroll').scrollTop=0;}$('#prev').onclick=()=>movePage(-1);$('#next').onclick=()=>movePage(1);
function evidence(i,id){const hits=F.rows[i].actions[id];const caution=id==='rescue'?'<p class="detail-meta">Rescue / add-back is an abstract wording flag. It does not distinguish genetic complementation, metabolite supplementation or general phenotype restoration. Check the experimental design in the full text.</p>':'';return caution+(hits.length?hits.map(h=>`<blockquote><small>${h.tentative?'Contains tentative wording':'Text match · experimental use requires review'}</small>${E(h.text)}</blockquote>`).join(''):'<p class="muted">No matching wording was found in this abstract. This does not establish that the action was absent from the study.</p>');}
function paper(i,selectedAction=null){const p=D.papers[i],r=F.rows[i],subtype=r.subtype?(r.subtype.includes('遗传')?'Genetic / synthetic microbial engineering':'Materials / delivery design'):'';return `<article><div class="detail-meta">${E(p.id)} · ${E(p.year||'Year unavailable')}</div><h3>${E(p.title)}</h3><p class="detail-meta">${E(p.author)} · ${E(p.journal)}</p><div class="detail-labels"><span>Primary: ${names[r.primary]}</span>${r.secondary.map(s=>`<span>Secondary: ${names[s]}</span>`).join('')}${subtype?`<span>${subtype}</span>`:''}</div><p class="detail-meta">Automatic candidate classification · not yet manually confirmed</p>${p.doi?`<p><a href="https://doi.org/${encodeURIComponent(p.doi)}" target="_blank" rel="noopener">Read paper ↗</a></p>`:''}${selectedAction?`<section class="selected-action"><h3>${actionNames[selectedAction]}</h3>${evidence(i,selectedAction)}</section>`:''}<details><summary>Original abstract</summary><blockquote>${E(p.abstract)}</blockquote></details>${F.actions.filter(a=>r.actions[a.id].length&&a.id!==selectedAction).map(a=>`<details><summary>${actionNames[a.id]} <span class="muted">· ${r.actions[a.id].length} sentences</span></summary>${evidence(i,a.id)}</details>`).join('')}</article>`;}
function show(i,j=null,a=null){const compare=j!==null&&i!==j;$('#dialog-title').textContent=compare?'Compare two papers':a?actionNames[a]:'Paper details';$('#detail').innerHTML=(compare?`<div class="compare-score">Abstract similarity <strong>${sim(i,j).toFixed(3)}</strong> · Similarity alone does not establish shared mechanisms or conceptual lineage.</div>`:'')+`<div class="paper-grid ${compare?'compare':''}">${paper(i,a)}${compare?paper(j):''}</div>`;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;$('#close-dialog').focus();}
$('#close-dialog').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}};
function position(e){if(!geometry)return null;const r=canvas.getBoundingClientRect(),g=geometry,x=(e.clientX-r.left)/r.width*g.size,y=(e.clientY-r.top)/r.height*g.size;if(x<g.pad||y<g.pad||x>=g.pad+g.plot||y>=g.pad+g.plot)return null;return [Math.floor((y-g.pad)/g.plot*g.m),Math.floor((x-g.pad)/g.plot*g.m)];}
function hint(p){$('#hover').textContent=`${D.papers[order[p[0]]].id} × ${D.papers[order[p[1]]].id} · similarity ${sim(order[p[0]],order[p[1]]).toFixed(3)}`;}
canvas.onclick=e=>{const p=position(e);if(p){activeCell=p;show(order[p[0]],order[p[1]]);}};canvas.onmousemove=e=>{const p=position(e);if(p)hint(p);};canvas.onkeydown=e=>{if(!order.length)return;const keys={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]};if(keys[e.key]){e.preventDefault();keyboardSelection=true;activeCell=activeCell.map((v,i)=>Math.max(0,Math.min(order.length-1,v+keys[e.key][i])));hint(activeCell);draw();}else if(e.key==='Enter'){e.preventDefault();show(order[activeCell[0]],order[activeCell[1]]);}};
new ResizeObserver(draw).observe($('.matrix-stage'));update();
})();
