const organNames={'乳腺':'Breast','肝脏':'Liver','肺':'Lung'};
const focusNotes={
'ITB-000078':'Spatial meta-transcriptomics connects bacterial burden with distinct oncogenic signatures in lung cancer cells.',
'ITB-000048':'A study of gut-to-liver translocation of Klebsiella pneumoniae and its role in hepatocellular carcinoma.'
};
const all=window.PAPERS.map(p=>({...p,organ:organNames[p.organ]||p.organ,short:p.title,summary:focusNotes[p.id]||'',review:'Full-text review is pending, including contamination controls, localization, independent validation and causal evidence.'}));let organ='All',limit=8;const colors={'Breast':'#b83b35','Liver':'#b58a36','Lung':'#277b88'};const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const selected=()=>all.filter(p=>organ==='All'||p.organ===organ);const short=p=>p.short||p.title;const btn=p=>'<button class="paper-open" data-id="'+p.id+'">'+esc(short(p))+'</button>';
function detail(id){const p=all.find(p=>p.id===id);$('#detail').innerHTML='<span class="eyebrow">'+esc(p.organ)+' / '+p.year+' / '+esc(p.id)+'</span><h2>'+esc(p.title)+'</h2><p class="meta">'+esc(p.author)+' · '+esc(p.journal)+'</p><p>'+esc(p.summary||'Basic record available. Detailed interpretation is pending.')+'</p><p class="small">Citations: '+(p.citations??'Unavailable')+' · OpenAlex，9 September 2026</p><hr><p><b>Technical rigor</b>　Full-text assessment pending</p><p><b>Conceptual novelty</b>　Full-text assessment pending</p><p class="small">'+esc(p.review||'Contamination controls, independent validation and causal evidence remain to be reviewed.')+'</p>'+(p.doi?'<a class="doi" target="_blank" rel="noopener" href="https://doi.org/'+encodeURIComponent(p.doi)+'">Read the paper ↗</a>':'');$('#paper-dialog').showModal()}
function render(){const papers=selected().sort((a,b)=>b.year-a.year||b.id.localeCompare(a.id));$('#inventory').textContent=all.length+' records · 3 organ collections';$('#selection-label').textContent=(organ==='All'?'All organs':organ)+' · '+papers.length+' papers';document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.organ===organ);b.setAttribute('aria-pressed',b.dataset.organ===organ)});const preferred=['ITB-000078','ITB-000048'];let focuses=preferred.map(id=>papers.find(p=>p.id===id)).filter(Boolean);for(const p of [...papers].sort((a,b)=>(b.citations??0)-(a.citations??0))){if(focuses.length>=2)break;if(!focuses.includes(p))focuses.push(p)}$('#focus').innerHTML=focuses.map(p=>'<article class="focus-item"><span class="eyebrow">'+esc(p.organ)+' · '+esc(p.journal)+'</span><h3>'+btn(p)+'</h3><p class="summary">'+esc(p.summary||'Explore the study design and its central research question.')+'</p><span class="meta">'+esc(p.author)+' / '+p.year+'<br>Citations: '+(p.citations??'Unavailable')+' · Basic record</span></article>').join('');$('#recent').innerHTML=papers.slice(0,6).map(p=>'<article class="recent-item"><div class="meta">'+p.year+' · '+esc(p.organ)+' / '+esc(p.author)+'</div><h3>'+btn(p)+'</h3></article>').join('');$('#papers').innerHTML=papers.slice(0,limit).map(p=>'<tr><td>'+p.year+'<br><span class="small">'+esc(p.organ)+'</span></td><td><button class="paper-open" data-id="'+p.id+'">'+esc(p.title)+'</button></td><td>'+esc(p.journal)+'</td><td>'+(p.citations??'—')+'</td><td>Basic record</td></tr>').join('');$('#more').hidden=limit>=papers.length;chart(papers)}
function chart(papers){const data=papers.filter(p=>Number.isFinite(p.citations));const min=Math.min(2014,...all.map(p=>p.year)),max=2026;const ceiling=Math.max(100,Math.ceil(Math.max(...data.map(p=>p.citations),0)/100)*100);let html='';for(let i=0;i<=4;i++){let y=230-i*50;html+='<line x1="55" y1="'+y+'" x2="735" y2="'+y+'" stroke="#e7e7e7"/><text x="44" y="'+(y+4)+'" text-anchor="end">'+Math.round(i*ceiling/4)+'</text>'}for(let year=min;year<=max;year+=2){const x=60+(year-min)/(max-min)*670;html+='<text x="'+x+'" y="257" text-anchor="middle">'+year+'</text>'}data.forEach((p,i)=>{let x=60+(p.year-min)/(max-min)*670+(i%5-2)*3,y=230-p.citations/ceiling*200;html+='<circle class="dot" tabindex="0" role="button" aria-label="'+esc(short(p))+'" data-id="'+p.id+'" cx="'+x+'" cy="'+y+'" r="4.5" fill="'+colors[p.organ]+'" opacity=".68"><title>'+esc(p.author)+' '+p.year+' · '+p.citations+' citations</title></circle>'});$('#chart').innerHTML=html}
document.addEventListener('click',e=>{const o=e.target.closest('[data-organ]');if(o){organ=o.dataset.organ;limit=8;render()}const p=e.target.closest('[data-id]');if(p)detail(p.dataset.id)});$('#chart').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.id){e.preventDefault();detail(e.target.dataset.id)}});$('.close').onclick=()=>$('#paper-dialog').close();$('#paper-dialog').addEventListener('click',e=>{if(e.target===$('#paper-dialog'))$('#paper-dialog').close()});$('#more').onclick=()=>{limit+=12;render()};render();
