const START=Date.UTC(2025,0,1),END=Date.UTC(2026,8,9),SPAN=END-START;
const papers=window.PAPERS.filter(p=>Number.isFinite(p.citations)&&p.citations<100&&Number.isFinite(p.jif)&&p.publishedOn>='2025-01-01'&&p.publishedOn<='2026-09-09').map(p=>({...p,date:Date.parse(p.publishedOn.length===7?p.publishedOn+'-01':p.publishedOn)})).filter(p=>Number.isFinite(p.date));
const presets=[
  {name:'Fine core',core:1.15,opacity:.16,scale:1.05,mode:'flat',copy:'The position dominates; JIF stays quiet.'},
  {name:'Balanced',core:2,opacity:.18,scale:1.1,mode:'flat',copy:'A moderate center with an even translucent field.'},
  {name:'Strong core',core:3,opacity:.12,scale:1.1,mode:'flat',copy:'High positional certainty with restrained context.'},
  {name:'Soft gradient',core:1.8,opacity:.26,scale:1.1,mode:'gradient',copy:'The halo fades smoothly instead of ending at a ring.'},
  {name:'Broad gradient',core:1.45,opacity:.2,scale:1.48,mode:'gradient',copy:'More atmospheric, with wider JIF separation.'},
  {name:'Double halo',core:1.8,opacity:.2,scale:1.2,mode:'double',copy:'Two soft layers preserve size without a hard edge.'}
];
const x=p=>50+(p.date-START)/SPAN*525,y=p=>180-p.citations/100*135,base=p=>Math.max(2.2,1.4*Math.sqrt(p.jif));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function axes(id){let h=`<defs><radialGradient id="g-${id}"><stop offset="0" stop-color="#687174" stop-opacity="1"/><stop offset="55%" stop-color="#899194" stop-opacity=".58"/><stop offset="100%" stop-color="#aab0b2" stop-opacity="0"/></radialGradient></defs>`;for(let i=0;i<=4;i++){const yy=180-i*33.75;h+=`<line class="gridline" x1="50" y1="${yy}" x2="575" y2="${yy}"/><text class="axis-label" x="42" y="${yy+3}" text-anchor="end">${i*25}</text>`;}[['Jan 25',START],['Jul 25',Date.UTC(2025,6,1)],['Jan 26',Date.UTC(2026,0,1)],['Jul 26',Date.UTC(2026,6,1)]].forEach(([label,date])=>h+=`<text class="axis-label" x="${50+(date-START)/SPAN*525}" y="204" text-anchor="middle">${label}</text>`);return h;}
function marks(config,id){return papers.slice().sort((a,b)=>base(b)-base(a)).map(p=>{const cx=x(p),cy=y(p),radius=base(p)*config.scale,common=`data-id="${p.id}" class="point"`;
  if(config.mode==='gradient')return `<g ${common}><circle cx="${cx}" cy="${cy}" r="${radius}" fill="url(#g-${id})" opacity="${config.opacity}"/><circle cx="${cx}" cy="${cy}" r="${config.core}" fill="#202426"/></g>`;
  if(config.mode==='double')return `<g ${common}><circle cx="${cx}" cy="${cy}" r="${radius*1.28}" fill="#778084" opacity="${config.opacity*.38}"/><circle cx="${cx}" cy="${cy}" r="${radius*.76}" fill="#778084" opacity="${config.opacity}"/><circle cx="${cx}" cy="${cy}" r="${config.core}" fill="#202426"/></g>`;
  return `<g ${common}><circle cx="${cx}" cy="${cy}" r="${radius}" fill="#778084" opacity="${config.opacity}"/><circle cx="${cx}" cy="${cy}" r="${config.core}" fill="#202426"/></g>`;}).join('');}
function plot(config,id){return axes(id)+marks(config,id)}
document.querySelector('#preset-grid').innerHTML=presets.map((p,i)=>`<article class="preset"><div class="preset-head"><div><span class="preset-num">0${i+1}</span><h2>${p.name}</h2><p>${p.copy}</p></div><span class="params">core ${p.core}px<br>${Math.round(p.opacity*100)}% ${p.mode}<br>halo ${p.scale.toFixed(2)}×</span></div><svg class="plot" viewBox="0 0 620 215" role="img" aria-label="${p.name} halo and core scatter plot">${plot(p,'preset-'+i)}</svg></article>`).join('');
const live=document.querySelector('#live-plot'),inputs=['core','opacity','scale','gradient'].map(id=>document.querySelector('#'+id));
function renderLive(){const core=+inputs[0].value,opacity=+inputs[1].value,scale=+inputs[2].value,gradient=inputs[3].checked,config={core,opacity,scale,mode:gradient?'gradient':'flat'};live.innerHTML=plot(config,'live');document.querySelector('#core-out').value=core.toFixed(1)+' px';document.querySelector('#opacity-out').value=Math.round(opacity*100)+'%';document.querySelector('#scale-out').value=scale.toFixed(2)+'×';document.querySelector('#live-label').textContent=core.toFixed(1)+' px core · '+Math.round(opacity*100)+'% '+(gradient?'gradient':'flat')+' halo · '+scale.toFixed(2)+'×';}
inputs.forEach(input=>input.addEventListener('input',renderLive));renderLive();
const tooltip=document.querySelector('#tooltip'),byId=new Map(papers.map(p=>[p.id,p]));document.addEventListener('pointermove',event=>{const target=event.target.closest('.point');if(!target){tooltip.hidden=true;return}const p=byId.get(target.dataset.id);tooltip.innerHTML=`<b>${esc(p.title)}</b><span>${esc(p.organ)} · ${p.citations} citations · 2025 JIF ${p.jif.toFixed(1)}</span>`;tooltip.hidden=false;const box=tooltip.getBoundingClientRect();tooltip.style.left=Math.max(8,Math.min(innerWidth-box.width-12,event.clientX+14))+'px';tooltip.style.top=Math.max(8,Math.min(innerHeight-box.height-12,event.clientY+14))+'px';});
