(()=>{
const read=window.READING_SET,byId=Object.fromEntries(read.papers.map(p=>[p.id,p])),q=s=>document.querySelector(s),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tracks=[
{id:'L1',label:'Signal & reality',title:'What makes a microbial signal real?',intro:'Culturing and tissue localization establish presence. Contamination-aware analysis asks which signals survive scrutiny.',relation:0,groups:[
['Detect and culture','2006–16',['P27','P25','P40','P18'],'Bacteria can be detected in tissue; some isolates can be grown.','Culture supports viability in some samples. DNA abundance alone does not.'],
['Locate within tissue','2020–22',['P24','P29'],'Add tissue localization and broaden the sampling context.','Classification performance is a separate claim from microbial presence.'],
['Reassess the signal','2021–26',['P10','P28','P09'],'Ask how contamination, read assignment and transformations alter the result.','These analyses address different datasets and methods; they are not a single replication series.']]},
{id:'L2',label:'Selective niches',title:'Why do particular bacteria belong here?',intro:'A difference in community composition becomes a question about sampling, selective colonization and strain-level function.',relation:4,groups:[
['Observe enrichment','2011–14',['P39','P38','P17'],'Tumor and non-tumor samples contain different communities.','Cross-sectional differences do not establish that the tumor selected the bacteria.'],
['Define the niche','2017–19',['P30','P31','P11'],'Distinguish tissue, mucosal and other sampling environments.','Predicted metabolic capacity is not direct measurement of a causal metabolite.'],
['Resolve the organism','2020–24',['P13','P15'],'Move from a species label to adhesion and specific bacterial clades.','Colonization mechanisms and clade-specific enrichment are complementary branches.']]},
{id:'L3',label:'Location & function',title:'How does location become function?',intro:'From bacteria inside tumors to what they do inside cells—and why their position can change the outcome.',relation:0,groups:[
['Establish persistence and location','2017–20',['P23','P24'],'Persistent viable bacteria and intracellular localization provide a basis for asking about function.','Persistence and localization alone do not demonstrate that bacteria travel with tumor cells.'],
['Test a cellular consequence','2022',['P05','P14'],'Metastatic survival and spatial cell states turn location into a functional question.','Fu tests shear-stress survival; Galeano Niño studies local spatial and cellular heterogeneity.'],
['Add position and time','2024–26',['P07','P08'],'Longitudinal profiles and intracellular versus extracellular comparisons add conditions to the claim.','Longitudinal association and experimentally tested immune mechanisms are distinct evidence types.']]},
{id:'L4',label:'Immune direction',title:'When do microbes help—or hinder—immunity?',intro:'An immune effect needs a context: the metabolite, the responding host cell, and where the bacterium is located.',relation:2,groups:[
['Perturb the community','2018–19',['P37','P04'],'Depletion and transfer connect community changes with tumor and immune phenotypes.','Systemic antibiotics and FMT affect more than the local tumor ecosystem.'],
['Identify the responding cell','2020–23',['P21','P32','P33'],'Resolve distinct pathways through dendritic, stromal and T-cell-related responses.','These branches do not support one universal pro- or antitumor direction.'],
['Explain opposite outcomes','2022–26',['P12','P06','P08'],'Compare cell-specific AhR effects and location-dependent bacterial interactions.','A conditional contrast refines a claim; it does not automatically refute an earlier study.']]},
{id:'L5',label:'Molecular effects',title:'Which bacterial function changes the outcome?',intro:'Move beyond a bacterial name to an enzyme, a host signaling pathway or a metabolite that can be manipulated.',relation:null,groups:[
['Connect isolates to phenotypes','2016–23',['P26','P19','P20'],'Examine DNA damage, proliferative signaling and metabolic changes.','These are different functional branches, with different degrees of mechanistic resolution.'],
['Test a route to resistance','2017–23',['P22','P03'],'Drug metabolism and lactate-associated effects offer two routes to treatment resistance.','Enzyme deletion and complementation differ from metabolite addition; necessity must be assessed separately.'],
['Bridge to patient response','2019',['P36'],'Ask whether bacterial burden relates to treatment response in patients.','A mechanism in another organism or drug setting cannot fill this study’s causal gap.']]},
{id:'L6',label:'Clinical prediction',title:'Can a microbial marker predict what happens next?',intro:'Compare the same ambition across papers: a useful signal beyond the dataset in which it was discovered.',relation:1,groups:[
['Discover a candidate','2017–22',['P41','P02','P29'],'Explore classification in sputum, airway brushings and liver tissue.','Different sampling sites are not interchangeable; case classification is not population screening.'],
['Relate it to prognosis','2016–22',['P35','P34','P04','P16','P01'],'Test microbial burden or composition against patient outcomes.','P34 primarily concerns normal tissue; P16 has a different Fn direction; P01 reports external validation.'],
['Extend to treatment response','2019–23',['P36','P33'],'Take the question from general prognosis to response under treatment.','The P35–P36 extension is explicit. Similar questions elsewhere do not imply independent replication.']]}
];
const relationText=[
['Localization → functional extension','Fu 2022 explicitly starts from Nejman 2020’s intracellular localization, then tests cellular function in a spontaneous breast-tumor model.'],
['Prognosis → treatment response','The later ESCC study explicitly recalls its earlier Fn–survival finding and extends the question to chemotherapy response and recurrence.'],
['A contrast that narrows the claim','Bender 2023 directly discusses the earlier myeloid-cell AhR result alongside its CD8 T-cell finding. Cell and cancer context change the interpretation.'],
['An inherited method, a new question','Yao 2026 explicitly adapts Fu 2022’s low-input RNA-seq method. The functional and immune questions are related but distinct.'],
['Method continuity, finer resolution','Zepeda-Rivera 2024 uses the earlier isolation method and resolves the Fn enrichment question into bacterial clades.']
];
const ref=id=>{const p=byId[id];return `<button class="paper-ref" data-reading="${id}">${escape(p.authors[0]?.lastName||id)} ${p.year}</button>`};
function draw(id){const t=tracks.find(x=>x.id===id),members=[...new Set(t.groups.flatMap(g=>g[2]))];q('#trajectory-picker').innerHTML=tracks.map(x=>`<button data-track="${x.id}" aria-pressed="${x.id===id}">${x.label}</button>`).join('');q('#trajectory-lead').innerHTML=`<span class="eyebrow">QUESTION ${id.slice(1).padStart(2,'0')} / ${members.length} PAPERS</span><h2>${t.title}</h2><p>${t.intro}</p>`;q('#trajectory-stages').innerHTML=t.groups.map((g,i)=>`<article class="path-stage"><div class="stage-number">0${i+1}<span>${g[1]}</span></div><div><h3>${g[0]}</h3><p>${g[3]}</p><div>${g[2].slice(0,3).map(ref).join('')}${g[2].length>3?`<a class="paper-ref" href="#claim-families">+${g[2].length-3} more</a>`:''}</div></div></article>`).join('');q('#family-title').textContent=t.title;q('#family-scope').textContent=members.length+' papers / 3 claim groups';q('#family-table').innerHTML='<div class="claim-grid grid-head"><span>SHARED CLAIM</span><span>READ TOGETHER</span><span>WHAT EACH GROUP ADDS</span></div>'+t.groups.map(g=>`<article class="claim-grid"><div><h4>${g[0]}</h4><span class="small">${g[1]} · ${g[2].length} papers</span></div><div>${g[2].map(ref).join('')}</div><div><p>${g[3]}</p><p class="constraint">${g[4]}</p></div></article>`).join('');if(t.relation!==null){const r=read.relations[t.relation],rt=relationText[t.relation];q('#connection-strip').innerHTML=`<div><span class="eyebrow">A DOCUMENTED CONNECTION</span><h3>${rt[0]}</h3><div class="connection-papers">${ref(r.source)}<span>→</span>${ref(r.target)}</div></div><div><p>${rt[1]}</p><button class="proof" data-relation="${t.relation}">Read the passage behind this connection ↗</button></div>`}else q('#connection-strip').innerHTML='<div><span class="eyebrow">PARALLEL MECHANISMS</span><h3>Related questions, distinct routes.</h3></div><p>These papers are grouped by the outcome they explain. No direct paper-to-paper inheritance is claimed for this selection.</p>';
}
function openReading(id){const p=byId[id],record=all.find(x=>String(x.doi||'').toLowerCase()===p.doi.toLowerCase());if(record){detail(record.id);return}q('#detail').innerHTML=`<span class="eyebrow">READING SET · ${p.year}</span><h2>${escape(p.title)}</h2><p>${escape(p.authors[0]?.lastName)} · ${escape(p.journal)}</p><a class="doi" href="https://doi.org/${encodeURIComponent(p.doi)}" target="_blank" rel="noopener">Read the paper ↗</a>`;q('#paper-dialog').showModal()}
document.addEventListener('click',e=>{const t=e.target.closest('[data-track]');if(t)draw(t.dataset.track);const b=e.target.closest('[data-reading]');if(b)openReading(b.dataset.reading);const rel=e.target.closest('[data-relation]');if(rel){const i=+rel.dataset.relation,r=read.relations[i];q('#detail').innerHTML=`<span class="eyebrow">DOCUMENTED RELATIONSHIP</span><h2>${relationText[i][0]}</h2><p class="source-intro">${relationText[i][1]}</p>${r.passages.map(id=>{const p=read.sources[id];return `<blockquote class="demo-proof"><small>${escape(byId[p.paper_id].authors[0]?.lastName)} ${byId[p.paper_id].year} · PDF page ${p.page}</small>${escape(p.text)}</blockquote>`}).join('')}<p class="small">The passage supports the stated relationship. It does not establish priority across all literature.</p>`;q('#paper-dialog').showModal()}});
draw('L3');
})();
